"""Stable host contract used by detached GUI pages."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class AppHostProtocol(Protocol):
    is_collecting: bool
    product_var: str

    def load_product_cfg(self, product_name: str) -> bool: ...

    def reload_protocols(self) -> None: ...

    def report_error(self, title: str, exc: BaseException) -> None: ...

    def set_status(self, message: str) -> None: ...

    def send_generated_frame(self, frame: bytes, label: str = ...) -> bool: ...

    def sync_collector_cfg(self) -> None: ...

    def notify_ui_error(self, message: str) -> None: ...

    def get_product_catalog(self) -> tuple[dict[str, Path], dict[str, str]]: ...

    def get_monitoring_page_index(self) -> int | None: ...

    def clear_mcu_product_state(self) -> None: ...

    def get_collector(self) -> Any: ...

    def get_attr_center(self) -> Any: ...

    def get_cmd_engine(self) -> Any: ...

    def get_auto_reply(self) -> Any: ...

    def get_protocol_dir(self) -> Path: ...
